### ISSUE TITLE
About the vertical direction coordinate encoding in coord_handler.py

### ISSUE THREAD

**Issue by rootSue** [hubert0527/infinityGAN#10]
https://github.com/hubert0527/infinityGAN/blob/86e4715cbea2cc0940954bf646d3957454d4e5ed/coord_handler.py#L99

1. Why do you use self.ts_spatial_size instead of self.ss_spatial_size in the denominator? Is it a mistake or a special design?
2. If it is a special design, could you please explain it?  Thanks.

**Comment by hubert0527** [comment]
It is to reduce the test-time numerical domain gap. The size difference between texture syn input and the structure syn input can be seen as kind of a pre-padding. And we want such region to be at the saturated region (0.995 to 1 after tanh) of tanh, and so that when we extrapolate vertical coordinates at testing, the coordinates wont be too far away from it's training distribution (~1).

**Comment by hubert0527** [comment]
This figure may explain a bit of the concept, the red line is the result of the dividing by ss_spatial_size, and the green line is using the ts_spatial_size. Each color has three lines representing three different sizes of the features. The horizontal axis is the raw coordinate value, and the vertical axis is the value after tanh projection.

![image](https://user-images.githubusercontent.com/17472642/164072537-87710aa2-9322-4494-8772-d3eda4613a6b.png)

**Comment by rootSue** [comment]
OK, I got it. Thanks for the explanation.
